// Drives the real Reader, mounted as a video series, against the demo HLS
// stream generated by `pnpm demo:video`.
//
//   node scripts/episode-test.mjs
//
// Needs `pnpm dev` running.
//
// What it proves:
//   - the episode picker appears under the player, not only in the contents
//   - it opens on the episode actually being watched, not on episode 1
//   - the dropdown jumps to the chosen episode and the title follows
//   - the ‹ › buttons step one episode at a time and disable at the ends
//   - a reader with no sibling list is not given a useless one-episode picker
//
// The previous harness (reader-preview.html) re-implements the reader's markup
// by hand, so it cannot catch a change to the real component; this one mounts
// the real Reader, which is why it can fail when the reader regresses.

import { chromium } from "playwright";
import { mkdir } from "node:fs/promises";
import path from "node:path";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "test-results");
const url =
  process.env.EPISODE_PREVIEW_URL || "http://localhost:1420/video-reader-preview.html";

await mkdir(outDir, { recursive: true });

const browser = await chromium.launch({
  // The bundled Chromium is not downloaded here; the system Edge is the same
  // engine and is always present on Windows.
  channel: process.env.EPISODE_TEST_CHANNEL || "msedge",
});
const page = await browser.newPage({ viewport: { width: 1100, height: 900 } });
let failed = false;

try {
  await page.goto(url, { waitUntil: "domcontentloaded", timeout: 20000 });

  // hls.js attaches asynchronously, so the extras bar appears only once the
  // manifest has parsed.
  await page.waitForSelector(".player-wrap video", { timeout: 20000 });

  // -- the picker is there --------------------------------------------------
  const picker = page.locator(".episodes");
  assert.equal(await picker.count(), 1, "no episode picker rendered for a 5-episode series");
  await picker.waitFor({ state: "visible", timeout: 10000 });
  console.log("  episode picker rendered under the player");

  // It must reflect the episode being watched. The harness opens episode 3.
  const count = (await page.locator(".episodes-count").innerText()).trim();
  assert.equal(count, "第 3 / 5 集", `picker opened on the wrong episode: ${count}`);
  console.log(`  counter reads ${count}`);

  const selected = await page.evaluate(
    () => document.querySelector(".episodes-select option:checked")?.textContent ?? "",
  );
  assert.ok(selected.startsWith("第 3 集"), `dropdown opened on ${selected}`);
  console.log(`  dropdown opened on ${selected}`);

  const prevDisabled = await page.locator('.episodes button[aria-label="上一集"]').isDisabled();
  const nextDisabled = await page.locator('.episodes button[aria-label="下一集"]').isDisabled();
  assert.ok(!prevDisabled, "上一集 should be available on episode 3 of 5");
  assert.ok(!nextDisabled, "下一集 should be available on episode 3 of 5");

  await page.screenshot({ path: path.join(outDir, "episodes.png") });
  console.log("  screenshot: test-results/episodes.png");

  // -- the dropdown jumps ---------------------------------------------------
  await page.selectOption(".episodes-select", { index: 4 });
  await page.waitForFunction(
    () => document.querySelector("h1")?.textContent?.includes("第 5 集"),
    null,
    { timeout: 10000 },
  );
  const last = (await page.locator(".episodes-count").innerText()).trim();
  assert.equal(last, "第 5 / 5 集", `dropdown did not switch episode (${last})`);
  const heading = (await page.locator("h1").innerText()).trim();
  assert.ok(heading.includes("第 5 集"), `heading did not follow (${heading})`);
  console.log(`  choosing the dropdown moved the reader to ${heading}`);

  // -- the ends disable -----------------------------------------------------
  const nextAtEnd = await page.locator('.episodes button[aria-label="下一集"]').isDisabled();
  assert.ok(nextAtEnd, "下一集 should be disabled on the last episode");

  await page.selectOption(".episodes-select", { index: 0 });
  await page.waitForFunction(
    () => document.querySelector("h1")?.textContent?.includes("第 1 集"),
    null,
    { timeout: 10000 },
  );
  const prevAtStart = await page.locator('.episodes button[aria-label="上一集"]').isDisabled();
  assert.ok(prevAtStart, "上一集 should be disabled on the first episode");
  console.log("  both ends disable their arrow instead of wrapping around");

  // -- stepping -------------------------------------------------------------
  await page.locator('.episodes button[aria-label="下一集"]').click();
  await page.waitForFunction(
    () => document.querySelector("h1")?.textContent?.includes("第 2 集"),
    null,
    { timeout: 10000 },
  );
  await page.locator('.episodes button[aria-label="上一集"]').click();
  await page.waitForFunction(
    () => document.querySelector("h1")?.textContent?.includes("第 1 集"),
    null,
    { timeout: 10000 },
  );
  console.log("  ‹ › step one episode at a time");

  // -- a standalone video gets no picker ------------------------------------
  // A trailer is a "series" of one. A dropdown with a single entry is noise, so
  // the picker must disappear along with the chapter buttons.
  await page.goto(`${url}?solo=1`, { waitUntil: "domcontentloaded", timeout: 20000 });
  await page.waitForSelector(".player-wrap video", { timeout: 20000 });
  await page.waitForTimeout(300);
  assert.equal(
    await page.locator(".episodes").count(),
    0,
    "a one-episode list should not get an episode picker",
  );
  assert.equal(
    await page.locator(".chapter-nav").count(),
    0,
    "a one-episode list should not get chapter navigation either",
  );
  console.log("  a standalone video gets neither a picker nor chapter buttons");
} catch (error) {
  failed = true;
  console.error("episode test failed:", error.message);
  try {
    await page.screenshot({ path: path.join(outDir, "episodes-failure.png") });
    console.error("  failure screenshot: test-results/episodes-failure.png");
  } catch {
    /* ignore */
  }
} finally {
  await browser.close();
}

process.exit(failed ? 1 : 0);