// A tiny fixture site served over HTTP for the native smoke test.
//
// The packaged app cannot reach the Vite dev server or `file://`, so there was
// no way to exercise the music or video player in the real binary — those paths
// were only ever covered by browser tests. This serves a page that genuinely
// contains audio and video so the app can be driven through them.
//
// Reuses the media generated by `pnpm demo:audio` and `pnpm demo:video`.
//
//   node scripts/fixture-server.mjs [port]
//
// Returns the port it bound to on stdout, then serves until killed.

import { createServer } from "node:http";
import { readFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const demoDir = path.join(root, "public", "demo");

const TYPES = {
  ".html": "text/html; charset=utf-8",
  ".m3u8": "application/vnd.apple.mpegurl",
  ".ts": "video/mp2t",
  ".vtt": "text/vtt",
  ".wav": "audio/wav",
  ".mp4": "video/mp4",
  ".json": "application/json",
};

/** A page with several playable tracks, plus links so a contents list exists. */
function musicPage(base) {
  const links = Array.from(
    { length: 5 },
    (_v, i) =>
      // Distinct hrefs: the engine de-duplicates links, so five identical ones
      // would collapse to a single entry and look like a single-page source.
      `<li><a href="/music.html?t=${i + 1}">第 ${i + 1} 首 测试曲目</a>` +
      `<audio src="${base}/demo/track-${(i % 3) + 1}.wav"></audio></li>`,
  ).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>音乐测试页</title></head>
<body><h1>音乐测试页</h1><ul>${links}</ul></body></html>`;
}

/** A page with an HLS video and a subtitle track. */
function videoPage(base) {
  return `<!doctype html><html><head><meta charset="utf-8"><title>视频测试页</title></head>
<body><h1>视频测试页</h1>
<video src="${base}/demo/hls/master.m3u8" controls>
  <track kind="subtitles" src="${base}/demo/hls/subs.vtt" srclang="zh" label="中文" default>
</video>
<ul>${[1, 2, 3, 4]
    .map((n) => `<li><a href="/video.html?t=${n}">第 ${n} 集</a></li>`)
    .join("")}</ul>
</body></html>`;
}

/** A page of links under a given heading, for category testing. */
function categoryPage(heading, count) {
  const links = Array.from(
    { length: count },
    (_v, i) => `<li><a href="/category.html?c=${encodeURIComponent(heading)}&n=${i + 1}">${heading} 第 ${i + 1} 条</a></li>`,
  ).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>${heading}</title></head>
<body><h1>${heading}</h1><ul>${links}</ul>
<p><a href="/category.html?c=${encodeURIComponent(heading)}&n=99">更多 ${heading}</a></p>
</body></html>`;
}

/** What the source's search endpoint returns. */
function searchPage(query) {
  const links = Array.from(
    { length: 3 },
    (_v, i) => `<li><a href="/search.html?q=${encodeURIComponent(query)}&n=${i + 1}">命中 ${i + 1}</a></li>`,
  ).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>搜索 ${query}</title></head>
<body><h1>搜索「${query}」</h1><ul>${links}</ul></body></html>`;
}

/** A plain article, for the reading path. */
function articlePage() {
  const paras = Array.from(
    { length: 12 },
    (_v, i) => `<p>这是第 ${i + 1} 段测试正文，用来把页面撑到需要滚动。排版与进度都靠它来验证。</p>`,
  ).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>文章测试页</title></head>
<body><h1>文章测试页</h1>${paras}</body></html>`;
}

const requested = Number(process.argv[2] || 0);

const server = createServer(async (req, res) => {
  const url = new URL(req.url, "http://127.0.0.1");
  const host = `http://127.0.0.1:${server.address().port}`;
  const path_ = url.pathname;

  // The app's document lives on its own origin, so the player fetches the
  // manifest and segments cross-origin. Real video CDNs send permissive CORS
  // headers; this fixture has to as well or hls.js is blocked before it starts.
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Headers", "*");

  const query = url.searchParams;
  const dynamic =
    path_ === "/category.html"
      ? categoryPage(query.get("c") || "分类", 5)
      : path_ === "/search.html"
        ? searchPage(query.get("q") || "测试")
        : null;

  const html =
    dynamic ??
    {
      "/music.html": musicPage(host),
      "/video.html": videoPage(host),
      "/article.html": articlePage(),
    }[path_];

  if (html) {
    res.writeHead(200, { "Content-Type": TYPES[".html"] });
    res.end(html);
    return;
  }

  // Everything else comes from public/demo.
  const file = path.join(demoDir, path_.replace(/^\/demo\//, "").replace(/^\//, ""));
  if (!file.startsWith(demoDir)) {
    res.writeHead(403).end("forbidden");
    return;
  }
  try {
    const info = await stat(file);
    if (!info.isFile()) throw new Error("not a file");
    const body = await readFile(file);
    res.writeHead(200, { "Content-Type": TYPES[path.extname(file)] ?? "application/octet-stream" });
    res.end(body);
  } catch {
    res.writeHead(404).end("not found");
  }
});

server.listen(requested, "127.0.0.1", () => {
  // The parent reads this line to learn the port when 0 was requested.
  console.log(server.address().port);
});

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => server.close(() => process.exit(0)));
}