// Development harness for the video player.
//
// Renders VideoPlayer against a real multi-bitrate HLS stream generated by
// `pnpm demo:video`, so HLS attachment, quality switching and speed control can
// be exercised in a real browser.
//
// Opened at /video-preview.html while `pnpm dev` is running. Never bundled.

import "./dev-tauri-stub";
import { StrictMode, useState } from "react";
import { createRoot } from "react-dom/client";
import { VideoPlayer, isPlayable } from "./components/VideoPlayer";
import type { Subtitle } from "./components/media";
import "./styles.css";

const STREAMS = [
  // Each stream carries its own `sourceId`, because that is what the subtitle
  // appearance is remembered against: one entry's big captions must not follow
  // the viewer into the next one.
  { label: "HLS 多码率", src: "/demo/hls/master.m3u8", id: "demo:master" },
  { label: "HLS 单码率 360p", src: "/demo/hls/360p.m3u8", id: "demo:360p" },
  { label: "损坏的源", src: "/demo/hls/missing.m3u8", id: "demo:broken" },
];

function Preview() {
  const [at, setAt] = useState(0);
  const [nextOn, setNextOn] = useState(true);
  const stream = STREAMS[at];
  const subs: Subtitle[] = [{ src: "/demo/hls/subs.vtt", label: "中文", lang: "zh", isDefault: true }];

  return (
    <div className="main" style={{ maxWidth: 860, margin: "30px auto", padding: "0 16px" }}>
      <div className="main-head">
        <div className="main-title">
          视频源预览
          <span>{stream.label}</span>
        </div>
        <span className="spacer" />
        <label style={{ fontSize: 12 }}>
          <input type="checkbox" checked={nextOn} onChange={(e) => setNextOn(e.target.checked)} /> 连播
        </label>
        <select value={at} onChange={(e) => setAt(Number(e.target.value))}>
          {STREAMS.map((s, i) => (
            <option key={s.src} value={i}>
              {s.label}
            </option>
          ))}
        </select>
      </div>
      <div className="main-body">
        <VideoPlayer
          src={stream.src}
          title={stream.label}
          resumeKey="demo:video"
          sourceId={stream.id}
          subtitles={subs}
          nextTitle={nextOn ? "第 2 集 · 示例" : undefined}
          onNext={nextOn ? () => console.log("[preview] autoplay next") : undefined}
        />
        {/* A real typing target: the shortcuts must get out of its way. */}
        <label style={{ display: "block", fontSize: 12, marginTop: 8 }}>
          备注（在这里打字时，快捷键应当让路）
          <input
            data-preview-note="1"
            type="text"
            defaultValue=""
            style={{ display: "block", width: 260, marginTop: 4 }}
          />
        </label>
        <p style={{ color: "var(--text-faint)", fontSize: 12 }}>
          isPlayable(/demo/hls/master.m3u8) = {String(isPlayable("/demo/hls/master.m3u8"))}
        </p>
      </div>
    </div>
  );
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <Preview />
  </StrictMode>,
);