// Development harness for the video player.
//
// Renders VideoPlayer against a real multi-bitrate HLS stream generated by
// `pnpm demo:video`, so HLS attachment, quality switching and speed control can
// be exercised in a real browser.
//
// Opened at /video-preview.html while `pnpm dev` is running. Never bundled.

import "./dev-tauri-stub";
import { StrictMode, useState } from "react";
import { createRoot } from "react-dom/client";
import { VideoPlayer, isPlayable } from "./components/VideoPlayer";
import "./styles.css";

const STREAMS = [
  { label: "HLS 多码率", src: "/demo/hls/master.m3u8" },
  { label: "HLS 单码率 360p", src: "/demo/hls/360p.m3u8" },
  { label: "损坏的源", src: "/demo/hls/missing.m3u8" },
];

function Preview() {
  const [at, setAt] = useState(0);
  const stream = STREAMS[at];

  return (
    <div className="main" style={{ maxWidth: 860, margin: "30px auto", padding: "0 16px" }}>
      <div className="main-head">
        <div className="main-title">
          视频源预览
          <span>{stream.label}</span>
        </div>
        <span className="spacer" />
        <select value={at} onChange={(e) => setAt(Number(e.target.value))}>
          {STREAMS.map((s, i) => (
            <option key={s.src} value={i}>
              {s.label}
            </option>
          ))}
        </select>
      </div>
      <div className="main-body">
        <VideoPlayer src={stream.src} title={stream.label} resumeKey="demo:video" />
        <p style={{ color: "var(--text-faint)", fontSize: 12 }}>
          isPlayable(/demo/hls/master.m3u8) = {String(isPlayable("/demo/hls/master.m3u8"))}
        </p>
      </div>
    </div>
  );
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <Preview />
  </StrictMode>,
);